### ISSUE TITLE
public/appConfig.js  missing accountSid variable

### ISSUE THREAD

**Issue by jobayersajal1** [twilio-labs/plugin-queued-callbacks-and-voicemail#12]
This is the exact step noted from this readme section.There it is instructed to update accountSid variable. But there is no  accountSid variable in appConfig.js (code 1). Assuming, I should add the extra variable I did as showed in code 1 (comment ) below.But, the react app didn't work,it didn't show  any callback option or voicemail after creating the task in flex.
Step 3: Open appConfig.js with your text editor and update the accountSid variable with your account SID:
var accountSid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

`//code 1
//assuming here I have to add this line "var accountSid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'"
var appConfig = {
  pluginService: {
    enabled: true,
    url: '/plugins',
  },
  ytica: false,
  logLevel: 'info',
  showSupervisorDesktopView: true,
};`

**Comment by bermudezmt** [comment]
Hello, this actually stopped being a requirement since Plugin Builder v2. Since you now have the ability to launch Flex from the Twilio Console, you no longer need to set your accountSID. I will update the README to reflect that. Also, you can follow a more detailed guide for this plugin at https://www.twilio.com/docs/flex/solutions-library/queued-callback-and-voicemail

Let me know if you run into any issues!

**Comment by bermudezmt** [comment]
Addressed by #14

**Comment by Softopolis** [comment]
H

> Addressed by #14



> Hello, this actually stopped being a requirement since Plugin Builder v2. Since you now have the ability to launch Flex from the Twilio Console, you no longer need to set your accountSID as a variable. I will update the README to reflect that. Also, you can follow a more detailed guide for this plugin at https://www.twilio.com/docs/flex/solutions-library/queued-callback-and-voicemail
> 
> Let me know if you run into any issues!

Hello, I have some questions about the plugin **"plugin-queued-callbacks-and-voicemail"** maybe you can help me. How Can I customize the plugin with my own file voice?. I need the same function but with female spanish voice. How can I change that?. Also it's possible to change the logic?. Thanks for you help.

**Comment by jobayersajal1** [comment]
@Softopolis As I did similar things you are doing, visit public/resources/functions/queue-menu.protected.js for changing voice and logic

**Comment by bermudezmt** [comment]
Hey, so awesome to see people helping each other here. 😄 @Softopolis let me know if you have follow-up questions.

Changing the logic is possible, but as this plugin is meant to be deployed as is, you may run into issues we haven't anticipated. For a detailed deployment guide for this plugin, please visit https://www.twilio.com/docs/flex/solutions-library/queued-callback-and-voicemail.

**Comment by bermudezmt** [comment]
Closing this issue as the documentation need has been addressed by #14. Please feel free to open another issue if you're still having trouble with the plugin.
