### ISSUE TITLE
Small Bug Fixes

### ISSUE THREAD

**Issue by tbooth-prog** [twilio-labs/plugin-queued-callbacks-and-voicemail#33]
Hi I've been working with the plugin and functions and they are great. As part of my use case I noticed a couple of small issues.

In serverless -> functions -> inqueue-voicemail.protected.js line 93 should be: 

`({ taskSid } = taskInfo);` rather than `({ taskSid } = taskInfo.taskSid);`
 
 
Also serverless -> functions -> queue-menu.protected.js line 130 it might be worth initiating the task info variable as an object with a status key as if both `getEwt` and `getQueuePosition` are set to false the function fails on the next conditional when it looks for `taskInfo.status`. For my use case I did the following: 

`let taskInfo = { status: "Not Requested" };`

Thanks for putting together a great solution

**Comment by vernig** [comment]
Hey @tbooth-prog thank you so much for catching those bugs! i'll prepare a PR for that shortly.

**Comment by vernig** [comment]
@tbooth-prog for the second point, I decided to swap the conditions in the `if` and make use of the [short-circuit evaluation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_AND#short-circuit_evaluation). 

I tested both and works fine for me. Let me know if it does for you.
