### ISSUE TITLE
Issue with plugin after deployment

### ISSUE THREAD

**Issue by jsandersj** [twilio-labs/plugin-queued-callbacks-and-voicemail#5]
I have the plugin compiled and deployed with the fix noted to a previous issue. Things seem to work fine except Place Outbound call for either Callback or Voicemail. When I click place outbound call I see this:

![image](https://user-images.githubusercontent.com/7594508/99846912-cfd7f180-2b3c-11eb-98ac-6bd3ff5da94d.png)

I do have legacy dialpad enabled. Behavior is same Firefox/Chrome. Is there somewhere else outbound dialing must be enabled?

**Comment by functionalStoic** [comment]
Hi @jsandersj,
That error is thrown when the Flex Native Dialpad is disabled in [Flex Settings](https://www.twilio.com/console/flex/settings). You can find instructions for enabling this feature here:
https://www.twilio.com/docs/flex/developer/dialpad/enable#enable-the-flex-dialpad-in-the-twilio-console

For reference, here is a screenshot of the section:
![Image 2020-11-20 at 4 08 08 PM](https://user-images.githubusercontent.com/7215306/99858360-9d34f580-2b4a-11eb-8c0f-ae53389b8ebc.png)

Let me know if you are still running into issues

**Comment by jsandersj** [comment]
My apologies, you are absolutely correct. And it was there as a requirement at the top of the document. I disable legacy, enable Flex Dialpad, and it works like a champ. Thank you so much for the quick response!
