### ISSUE TITLE
Delete Recordings Fails

### ISSUE THREAD

**Issue by jsandersj** [twilio-labs/plugin-queued-callbacks-and-voicemail#6]
When I choose voicemail, call is delivered, when I click on Delete Recordings, nothing happens. When console on, I see the following:

![image](https://user-images.githubusercontent.com/7594508/99847612-f3e80280-2b3d-11eb-8787-e24a757d1c20.png)

The 404 is expected as this is not the correct URL for this plugin. The console.log of the baseUrl on delivery of the call does show the correct value, but this is using an incorrect baseUrl value. See below for initial render of baseURL:

![image](https://user-images.githubusercontent.com/7594508/99847756-2db90900-2b3e-11eb-81ed-eded64b2919b.png)

**Comment by jsandersj** [comment]
Allow me to clarify...if you review 

InQueueVoicemailComponent.js

line 202 defines baseUrl as follows:

    const baseUrl =
      'https://' + this.props.manager.configuration.serviceBaseUrl;

In my case this line executes and defines baseURL as straw-mink-XXXX, and attempts to execute the 

https://straw-mink-XXXX.twil.io/inqueue-utils 

to delete the recording. However, this is an invalid URL. The function is deployed via twilio-cli to a domain of:

plugin-queued-callbacks-voicemail-functions-XXXX-dev.twil.io

So now, line 202 of 

InQueueVoicemailComponent.js

constructs a URL using that straw mink as base URL, which is valid as the base URL of my flex project, but NOT the base URL for where the 

inqueue-utils 

function lives. So...it returns a 404. On line 113, it defines baseUrl from environment variables, which I believe would be the desired behavior. Please let me know if that makes sense. Thanks!

**Comment by bermudezmt** [comment]
Thank you so much @jsandersj . This issue has been addressed by #10 .
