### ISSUE TITLE
[CRITICAL] Audio recording stuck in a loop, blocking customers from using the plugin

### ISSUE THREAD

**Issue by bermudezmt** [twilio-labs/plugin-queued-callbacks-and-voicemail#7]
After deploying the plugin, the audio is stuck in a loop and doesn't get past the "estimated wait time" message. Customers are unable to make a callback or voicemail request selection.

**Comment by bethfraser** [comment]
I'm also having this issue.

**Comment by bermudezmt** [comment]
Hi @bethfraser, that was actually my intuition as I've briefly looked into this. We've come up with an interim solution to get an older version of this plugin up and running for customers. I'll be curious to hear if you learn more about the TwiML + Send to Flex issue.

**Comment by strogzy** [comment]
I was able to work around the looping issue by replacing the Hold music URL's in queue-menu.protected.js to another URL. 
//gather.play(domain + '/assets/guitar_music.mp3');
gather.play('http://com.twilio.music.guitars.s3.amazonaws.com/Pitx_-_Long_Winter.mp3');

**Comment by aking-twilio** [comment]
Looks like there is a problem with the Guitar music file, swapping it out worked for me too @strogzy

**Comment by bermudezmt** [comment]
This has been addressed by #10 , with some amazing cleanup PR to follow from @ktalebian . 🎉
